### ISSUE TITLE
Reached max number of retries

### ISSUE THREAD

**Issue by GGGoingdown** [akhenakh/drone-waiton#1]
I encounter some problem when i set **globaltimeout** for 5m to make sure app service startup. But it always failed and show **reached max number of retries**.  How to ignored the **max number of retries value** or any other better solution. Thanks

```
- name: waiton app
  image: akhenakh/drone-waiton:1.0
  settings:
    globaltimeout: 5m
    urls:
      - http://app:8000/health
```
